### ISSUE TITLE
Error launching kartotherian for the first time

### ISSUE THREAD

**Issue by sujeebant** [QwantResearch/kartotherian_docker#57]
After cloning the repo and executing ```docker-compose -f docker-compose.yml -f local-compose.yml down -v ```
the kartotherian_docker_postgres_1 container shows an error :
```ERROR:  function z(numeric) does not exist at character 2890```

**Environment:**
Mac 10.13.3
Docker version 18.06.1-ce, build e68fc7a
docker-compose version 1.22.0, build f46880f
Docker images :
```
REPOSITORY                             TAG                 IMAGE ID            CREATED             SIZE
kartotherian_docker_tilerator-worker   latest              25680f883d43        About an hour ago   1.58GB
kartotherian_docker_tilerator          latest              25680f883d43        About an hour ago   1.58GB
kartotherian_docker_kartotherian       latest              dd4f01d932f2        About an hour ago   1.36GB
kartotherian_docker_load_db            latest              f40938086d20        About an hour ago   2.01GB
redis                                  latest              f1897cdc2c6b        9 hours ago         83.4MB
cassandra                              latest              66915988fef9        12 hours ago        323MB
qwantresearch/erdapfel                 latest              d0dc3898cccf        4 days ago          1.16GB
ubuntu                                 <none>              b9e15a5d1e1a        5 weeks ago         115MB
node                                   <none>              71d6f71e58d2        5 weeks ago         878MB
python                                 <none>              4f13b7f2138e        5 weeks ago         918MB
openmaptiles/postgis                   latest              f32a1706ca81        15 months ago       1.19GB
```

The logs of some of the containers are attached to the issue :
[kartotherian_docker_postgres_1.txt](https://github.com/QwantResearch/kartotherian_docker/files/2483356/kartotherian_docker_postgres_1.txt)
[kartotherian_docker_cassandra_1.txt](https://github.com/QwantResearch/kartotherian_docker/files/2483357/kartotherian_docker_cassandra_1.txt)
[kartotherian_docker_kartotherian_1.txt](https://github.com/QwantResearch/kartotherian_docker/files/2483358/kartotherian_docker_kartotherian_1.txt)
[kartotherian_docker_tilerator_1.txt](https://github.com/QwantResearch/kartotherian_docker/files/2483359/kartotherian_docker_tilerator_1.txt)
[kartotherian_docker_tilerator-worker_1.txt](https://github.com/QwantResearch/kartotherian_docker/files/2483360/kartotherian_docker_tilerator-worker_1.txt)

**Comment by antoine-de** [comment]
just to clarify, it is expected behavior, the errors should disappear if you import some data:

```
docker-compose -f docker-compose.yml -f local-compose.yml run --rm -e INVOKE_OSM_URL=https://download.geofabrik.de/europe/luxembourg-latest.osm.pbf -e INVOKE_TILES_X=66 -e INVOKE_TILES_Y=43 -e INVOKE_TILES_Z=7 load_db
```
(to generate tiles on luxembourg, if you want to generate other tiles, use another PBF and give the X/Y/Z of the tile you want (you can use [geofabrik tool](https://tools.geofabrik.de/calc/#6/51.25727/10.45457&type=Mapnik&grid=1) for this as stated in the readme)).
