### ISSUE TITLE
Over Simplification?

### ISSUE THREAD

**Issue by landc0ver** [QwantResearch/kartotherian_docker#66]
I ran the entire process locally to generate tiles for some countries. But I found that some geometries were over simplified in some area, such as Macau . I compared them to [Qwant Maps](https://www.qwant.com/maps) in the same area (as below), but the latter does not have this problem. 

![image](https://user-images.githubusercontent.com/49969356/56874960-359eed00-6a70-11e9-91af-b470ab526174.png)
![image](https://user-images.githubusercontent.com/49969356/56874979-57986f80-6a70-11e9-9b83-4e87acb81b32.png)

Moreover, I executed the process with default configurations, so how can I fix that? Thank you.

**Comment by amatissart** [comment]
It looks like you are seeing over-zoomed tiles. Are you sure the tiles generation was finished ?  
With the local configuration you can follow the jobs progress on http://localhost:16534/jobs/

**Comment by landc0ver** [comment]
> It looks like you are seeing over-zoomed tiles. Are you sure the tiles generation was finished ?
> With the local configuration you can follow the jobs progress on http://localhost:16534/jobs/

Thank you for your reply. You're right. The tiles are over-zoomed. When I tried to get tiles from source **basemap** instead of **ozbasemap**, I found that some tiles missed but they should have existed. But all jobs were done.
