### ISSUE TITLE
Missing file on load_db

### ISSUE THREAD

**Issue by lessrand** [QwantResearch/kartotherian_docker#68]
Hello there!

I am trying to get kartotherian running but i am stuck with an error message that the link http://data.openstreetmapdata.com/water-polygons-split-3857.zip is not valid any more.
I would like to replace it with http://osmdata.openstreetmap.de/download/water-polygons-split-3857.zip but i cannot find the file where to do this.

The readme says, that it will not download files that can be found in "the directiry" but it does not state which directory and how the data has to be presented.

could you please help me on this?

kind regards

Randolph

**Comment by lessrand** [comment]
I also copied the zip file to var/lib/docker/volumes/kartotheriandocker_input_data/_data/ but this did not help :-(

**Comment by lessrand** [comment]
Hello

As far as i can see it is one of the git dependencies pulling an old/invalif import-water.sh.
Is there a workaround for this problem?

kind regards

Randolph

**Comment by h1v3r** [comment]
Hi there, 
I am currently running into the same issue. I also tried to fix the problem by myself, however because of too many dependencies I was not able to fix the Problem. 

Thanks in advance for any help. 

Best regards,
Jakob

**Comment by amatissart** [comment]
Sorry for the late reply.  

The water polygons URL is now updated in our kartotherian_config repository (https://github.com/QwantResearch/kartotherian_config/pull/47).  
https://github.com/QwantResearch/kartotherian_docker/pull/69 will apply this change in docker images and should solve this issue.

On a side note, it's still possible to put the `water_polygons.shp` file (unzipped) in the "data" directory to avoid downloading the file from the server.
